// This file is automatically generated from your CSS. Any edits will be overwritten.
export const aligned: string;
export const alignGroup: string;
export const configBlock: string;
export const updateButton: string;
export const bigButton: string;
export const bigButtonRed: string;
export const addSensor: string;
export const topHeader: string;
export const mainContent: string;
export const col: string;
export const page: string;
export const toggleButton: string;
export const switchTheme: string;
