// This file is automatically generated from your CSS. Any edits will be overwritten.
export const graph: string;
export const filter: string;
export const bigButton: string;
export const popupContent: string;
export const popupArrow: string;
export const popupOverlay: string;
