# Generated by Django 4.0.5 on 2022-07-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=20, unique=True)),
                ("device_name", models.CharField(max_length=50)),
                ("hw_revision", models.CharField(default="4.0", max_length=10)),
                ("send_interval", models.IntegerField(default=1)),
                ("first_send_at", models.IntegerField(default=0)),
                (
                    "mqtt_host",
                    models.CharField(default="test.mosquitto.org", max_length=100),
                ),
                ("mqtt_port", models.IntegerField(default=1883)),
                ("mqtt_username", models.CharField(max_length=50)),
                ("mqtt_password", models.CharField(max_length=50)),
                (
                    "mqtt_parent_topic",
                    models.CharField(
                        default="test/environmentMonitoring/", max_length=100
                    ),
                ),
                ("mmw_auth_token", models.CharField(max_length=50)),
                ("mmw_sampling_feature", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SDI12Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("enabled", models.BooleanField()),
                ("address", models.IntegerField()),
                ("bootup_time", models.IntegerField(default=0)),
                ("record_interval", models.IntegerField(default=10)),
                ("first_record_at", models.IntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdi12_sensors",
                        to="configservice.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading", models.CharField(max_length=20)),
                ("index", models.IntegerField()),
                ("multiplier", models.IntegerField()),
                ("offset", models.IntegerField()),
                ("unit", models.CharField(max_length=10)),
                ("uuid", models.CharField(max_length=50)),
                (
                    "sdi12_sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="configservice.sdi12sensor",
                    ),
                ),
            ],
        ),
    ]
