// This file is automatically generated from your CSS. Any edits will be overwritten.
export const maintenanceBlock: string;
export const maintenancePopUp: string;
export const titleText: string;
export const bigButton: string;
